### ISSUE TITLE
Chore: Add Claudie to G2 and Capterra

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#1069]
We need to add Claudie, to two prominent software review websites, [G2](https://www.g2.com/) and [Capterra](https://www.capterra.com/), to increase our online visibility and reach potential customers.

**Comment by katapultcloud** [comment]
maybe we could add it here on [producthunt](https://www.producthunt.com/)

**Comment by bernardhalas** [comment]
Pending feedback from Capterra and ProductHunt

**Comment by JKBGIT1** [comment]
[Claudie on ProductHunt](https://www.producthunt.com/products/claudie). No feedback from Capterra yet.
