### ISSUE TITLE
Feature: Add node name to status information

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1116]
Currently when getting cluster information it looks like this:
```
kubectl get inputmanifests.claudie.io xxx -o jsonpath='{.status}' | jq .
{
  "clusters": {
    "wox-cluster": {
      "message": "installing VPN",
      "phase": "ANSIBLER",
      "state": "IN_PROGRESS"
    }
  },
  "state": "IN_PROGRESS"
}
```
It would be great if a node name code be added, something like:
```
kubectl get inputmanifests.claudie.io xxx -o jsonpath='{.status}' | jq .
{
  "clusters": {
    "wox-cluster": {
      "message": "installing VPN",
      "metadata": {
           "nodepool": "hel1",
           "node": "xxx-cluster-kk68r9o-control-hetzner-hel1-5hyuend-1"
       }
      "phase": "ANSIBLER",
      "state": "IN_PROGRESS"
    }
  },
  "state": "IN_PROGRESS"
}
```

**Comment by MiroslavRepka** [comment]
I am not sure if this would be possible. Last time I checked the code (~4months ago), Claudie was building input manifest on per cluster basis, meaning if you defined 2 cluster in same input manifest, they would be built concurrently. 

Thus the granularity we have in the message is also on per cluster base not per node/nodepool base.

**Comment by Despire** [comment]
As of now this wouldn't be possible. Our lower granularity is currently per cluster.

To get an indication as for which nodes are being currently worked on the only possible way, as of now, is to deploy claudie with `debug` logs and examing the logs of the services.
