### ISSUE TITLE
Bug: Incorrect `expected` value in autoscaler's log

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1159]
### Current Behaviour

This is the log from `autoscaler`. The `current` value was correct because there were 3 nodes from `compute-hd-auto-z0w1g1x` nodepool. However, the expected value was incorrect.

```
static_autoscaler.go:673] Decreasing size of compute-hd-auto-z0w1g1x, expected=10 current=3 delta=-7
```

### Expected Behaviour

If there are 3 nodes, and the autoscaler does not want to scale, it should have 3 in `expected`. If it wants to scale up, it should have 4, if it wants to scale down, it should have 2.

### Anything else to note

There might be a chance that this happened because `autoscaler` got OOMKilled multiple times while trying to scale.

**Comment by bernardhalas** [comment]
Hi @JKBGIT1 , IIRC, it turned out the log message was correct in the end and the understanding of the situation was wrong, right?

**Comment by JKBGIT1** [comment]
Hi @bernardhalas , I have read up on the messages about this topic and it seems like it. I think this [message](https://kubernetes.slack.com/archives/C05SW4GKPL3/p1702322414964509) confirms it the most.

**Comment by bernardhalas** [comment]
Closing as per the above.
