### ISSUE TITLE
Chore: Increase the limits of context-box and autoscaler

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1161]
### Description
Resources limits for `context-box`, `autoscaler-adapter`, and `cluster-autoscaler` aren't high enough to use Claudie in production.
![image](https://github.com/berops/claudie/assets/43497822/1be96186-711b-4c6a-8933-faca38564495)

To get rid of OOMKills in `context-box` and `autoscaler-adapter`, I have increased the resources following:

`context-box`:

- Request memory 50Mi -> 100Mi
- Limits memory: 100Mi -> 150Mi

`autoscaler-adapter`:

- Request memory: 50Mi -> 100Mi
- Limits memory: 100Mi -> 150Mi

### Exit criteria

- [ ] Come up with proper limits (possibly also requests)
- [ ] Change the limits (requests) in the source code

**Comment by JKBGIT1** [comment]
`cluster-autoscaler` might need around 300Mi, because 200Mi wasn't enough.

**Comment by bernardhalas** [comment]
An option would be to remove the limits completely.
