### ISSUE TITLE
Bug: Missing LoadBalancer SSH key in the Claudie Secret

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1164]
### Current Behaviour

Using the command below you will get the information about dynamic/static nodepools and one SSH key (`cluster_private_key`). I don't know if one should be able to use this SSH key to connect to the LoadBalancer created by Claudie, but it doesn't work. Eventually, we needed to obtain a different SSH private key directly from MongoDB to be able to connect to the LB.
```
kubectl get secrets -n claudie -l claudie.io/output=metadata -ojsonpath='{.items[0].data.metadata}' | base64 -d | jq
```

### Expected Behaviour

LoadBalancer SSH key should be included in the Claudie metadata secret or one should be able to use the `cluster_private_key` to connect to the LoadBalancer through SSH.

### Steps To Reproduce

1. Create K8s cluster with LoadBalancer
2. Get `cluster_private_key` from the Claudie metadata secret
3. Try to SSH into LB using `cluster_private_key`

### Anything else to note

Where can one get the public IP address of the LoadBalancer? The Claudie metadata secret contains only public IPs for dynamic and static nodepools.

**Comment by bernardhalas** [comment]
The Control plane and Worker plane nodes use the same SSH keys. Any reason why not using the same SSH key-pair for LBs as well?

**Comment by JKBGIT1** [comment]
No, LB can use the same SSH key-pair, but it isn't currently.

**Comment by bernardhalas** [comment]
If you agree, instead of adding current LB key into the secret, I'd recommend using the same key, which is already present in the secret and used for control plane and compute plane connections.

**Comment by JKBGIT1** [comment]
I definitely agree 👍
