### ISSUE TITLE
Bug: Caller does not know if the Builder is working properly

### ISSUE THREAD

**Issue by MiroslavRepka** [Berops/claudie#119]
### Current Behavior:
When a manifest is being processed, in a case where Builder unexpectedly fails and dies, Claudie does not detect this and continues to wait.

### Expected Behavior:

When a manifest is being processed, in a case where Builder unexpectedly fails and dies, the Claudie should detect it and should terminate due to error.

### Steps To Reproduce:

1. Run all services in any environment
2. Run the `testing-framework`
3. Intentionally stop Builder
4. The `testing-framework` will not stop and will continue waiting until the testing framework timeout 

### Anything else to note:

This might be happening with Scheduler as well since both of these services are implemented as clients. We need to find an optimal solution for checking if the client services are running or not.

**Comment by jaskeerat789** [comment]
not relevant anymore
