### ISSUE TITLE
Chore: Describe latency-induced topology limitations

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#1208]
### Description
We've seen that with high latency between nodes carrying the volume replicas, the longhorn volumes become degraded. We've also seen that above certain latency the consuming nodes of these volumes can have issues that surface as nodes in `NotReady` state (the issue is coming from the I/O subsystem though).

We should reflect on these limitations in the docs to advise the users on reliable topology and usage patterns.

### Exit criteria

- [ ] Declare the latency requirements for nodes hosting the Longhorn replicas in the docs
- [ ] Declare the latency requirements for nodes mounting the Longhorn volumes in the docs

**Comment by JKBGIT1** [comment]
closing this in favor of https://github.com/berops/claudie/issues/1192
