### ISSUE TITLE
Feature: Test GPU support across cloud providers

### ISSUE THREAD

**Issue by Despire** [berops/claudie#1212]
### Motivation

GPUs are useful for computation heavy parallel tasks

### Description

Test GPU support in various cloud providers for Claudie

### Exit criteria

- [ ] Research how GPUs can be made available for a claudie made kubernetes cluster
- [ ] GPU support for claudie supported cloud providers

**Comment by cloudziu** [comment]
Hey @Despire I wanted to ask if there are some additional steps required to use GPU instances in Claudie? So if you chose a GPU Image Instance will it get added to Claudie made cluster, or something will fail?

**Comment by Despire** [comment]
Hi, I'm not sure how it works with all of the providers, but for genesis you would need to additionally install GPU drivers in the startupscript when spinning up a VM. (They don't seem to offer a image with preinstalled drivers)

As for the other providers, If they have a ubuntu image with the necessary drivers this should theoretically work already. But I don't think anyone has tested this

**Comment by cloudziu** [comment]
So Claudie cluster will spinup, but GPU Drivers on the nodes will be missing, correct? If thats the case IMO I would left the driver installation part to the end user to handle. I can imagine where one user whants driver version `X.Y.Z` and another `A.B.C`

**Comment by Despire** [comment]
> So Claudie cluster will spinup, but GPU Drivers on the nodes will be missing, correct?

Yes.

**Comment by bernardhalas** [comment]
If the drivers will need to be installed by the user, I don't think autoscaling would work, unless the user can automate the GPU driver installation somehow, correct?

So if we consider GPU driver installation by the user - will he or she have a way to automate the driver installation and integrate this with autoscaler?

**Comment by cloudziu** [comment]
https://github.com/NVIDIA/gpu-operator
Just found this :D

**Comment by Despire** [comment]
> https://github.com/NVIDIA/gpu-operator

Yes, but I think that works under the assumption that the GPU drivers are installed on the VM

**Comment by cloudziu** [comment]
> Yes, but I think that works under the assumption that the GPU drivers are installed on the VM

Where else the drivers should be installed? I think that the drivers are ment to be installed on the VM's

**Comment by cloudziu** [comment]
From the operator docs:
> The GPU Operator allows administrators of Kubernetes clusters to manage GPU nodes just like CPU nodes in the cluster. 

> Note that the GPU Operator is specifically useful for scenarios where the Kubernetes cluster needs to scale quickly - for example provisioning additional GPU nodes on the cloud or on-prem and managing the lifecycle of the underlying software components. 

Correct me if I'm wrong but from what I understand, that operator is exactly a solution for the usecase we are discussing. It manages drivers on newly added nodes that do not have drivers installed on the OS

**Comment by cloudziu** [comment]
https://github.com/NVIDIA/k8s-device-plugin#prerequisites
Additional controller
