### ISSUE TITLE
Feature: Allow loadbalancer to target specific nodes or nodepools

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1224]
It would be great if the loadbalancer config also had a targetPools parameter. Claudie keeps the config up to date anyway, but instead of adding all nodes to the nginx config(or HA), only add the ones from the nodepools specified. 
That way i could still have nodes in different regions, and keep the traffic there, because of the loadbalancers only sending the traffic to specified nodes.

**Comment by bernardhalas** [comment]
https://docs.claudie.io/v0.6.6/input-manifest/api-reference/#role

we could consider introducing a replacement for the `target` field, that would accept a list of nodepools the LB should target.

e.g.:

```
targetNodepools:
  - azure-compute-asia-1
  - azure-compute-asia-2
  - gcp-arm-japan-1
```

**Comment by Danielss89** [comment]
That sounds very good!
