### ISSUE TITLE
Feature: Sanity checks on static nodes

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1225]
### Motivation
In the InputManifest users can add static nodes that do not fulfill the requirements to run as nodes of the K8s cluster. The static nodes might miss some dependencies or don't run some services. We have already experienced not running `systemd-resolved` service due to which the K8s nodes wasn't healthy, because the `/run/systemd/resolve/resolv.conf` wasn't created.

### Description
Before Claudie starts building a K8s cluster, it checks if all required services on the static nodes are running and if these nodes have installed the required dependencies. In case they don't the workflow won't even start.

### Exit criteria

- [ ] Implement sanity checks on static nodes

**Comment by bernardhalas** [comment]
Let's set the requirements in docs for now (e.g. referring the requirements in K8s docs). We might come back to this in the future.
