### ISSUE TITLE
Remove `scheduler` service

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#1247]
We were discussing the need of `scheduler` service in Claudie. 

Initialy it was created to manage which nodepools should increase/decrease in size based on for example: cloud costs.
At this stage this is handled by user and/or autoscaler node pools. 

Scope of this task:
- [ ] Update Claudie code and move the current `scheduler` workflow to other service - for example `context-box`/`claudie-operator`
- [ ] Review backward compatibility
- [ ] Update workflow documentation/diagrams

**Comment by Despire** [comment]
closed by https://github.com/berops/claudie/pull/1498
