### ISSUE TITLE
Feature: Automatic docs update

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1248]
### Motivation

Automatic update of the docs happens only at the release. There are times when we need to update the docs, but we don't want to make a release yet. In times like this, we have to do it manually. The manual docs update has setbacks in setting up the environment (Python versions, etc.), and therefore not everybody can do that.

### Description

It will be good to have some command, comment, or label that will start the automatic update of the docs in GH action.

An example:

- we add a label to the PR. Let's say we name it `automatic-docs-update`
- every commit to that PR will now start a GH action to update the docs automatically

### Exit criteria

- [ ] Implement a GH action for an automatic update of the docs
- [ ] Implement a trigger for that GH action

**Comment by bernardhalas** [comment]
I propose a label `/refresh-docs`. Shorter and still to the point :)
