### ISSUE TITLE
Bug: AWS account details failed to retrieve in higher TF version

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1250]
### Motivation
I am mostly opening this to spare some time when we decide to upgrade the TF version on Claudie.

### Current Behaviour
I ran `terraformer` [locally](https://github.com/berops/claudie/blob/master/docs/contributing/local-testing.md) because I wanted to use a debugger for development. I had a TF version `v1.7.2` and bumped into an error when initializing the TF project. This error also occurs on TF version `v1.7.4` (currently latest).
```
jakub-test-xckgd7f       │ Error: Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods.
jakub-test-xckgd7f       │ 
jakub-test-xckgd7f       │ See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications.
jakub-test-xckgd7f       │ Errors: 2 errors occurred:
jakub-test-xckgd7f       │      * retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.local.amazonaws.com/": dial tcp: lookup sts.local.amazonaws.com on 127.0.0.53:53: no such host
jakub-test-xckgd7f       │      * retrieving account information via iam:ListRoles: operation error IAM: ListRoles, https response error StatusCode: 403, RequestID: cdcacc3c-822a-430c-bedc-292aa99fb085, api error InvalidClientTokenId: The security token included in the request is invalid.
```
After downgrading TF to the `v1.5.7` version everything worked fine. 

**Potential fix** - to resolve this error in higher versions of TF. One needs to add `skip_requesting_account_id  = true` in the `backend.tf` for the `backend  "s3"` configuration ([see](https://github.com/hashicorp/terraform/issues/33983#issuecomment-1818849545)).

### Expected Behaviour
TF project successfully initialized.

### Steps To Reproduce
1. Run Claudie locally with TF version `v1.7.2`
2. Try to build a cluster

**Comment by bernardhalas** [comment]
We intend to migrate to OpenTofu for TF 1.5+. Let's keep this issue open to see if the bug reappears with OpenTofu 1.7.

**Comment by JKBGIT1** [comment]
I tried to replicate this bug on the current OpenTofu latest version (v1.6.2) and the bug didn't appear.

**Comment by JKBGIT1** [comment]
We are closing this one, because it isn't an issue in OpenTofu.
