### ISSUE TITLE
Chore: Support for newer versions of k8s

### ISSUE THREAD

**Issue by samuelstolicny** [berops/claudie#1278]
### Description.
Add support for newer versions of k8s 1.28, 1.29.

While testing Claudie, my management cluster bootstrapped from minikube (simply by `minikube start`) was already installed with k8s v1.28.3. I discovered that this version was not supported before I tried to apply a manifest, which is too late IMO.

Let's add support for the newer versions and mention the supported versions in the [Prerequisites](https://docs.claudie.io/latest/getting-started/detailed-guide/#prerequisites).

**Comment by JKBGIT1** [comment]
Hi @samuelstolicny , if the versioning you mentioned is related to the management cluster, Claudie can run on the versions you mentioned. A few minutes ago I ran Claudie on `kind` v1.29 and `minikube` 1.28.

**Comment by Despire** [comment]
update kube-one to never versions to support hight kubernetes version in claudie manifest

**Comment by JKBGIT1** [comment]
We are currently using the latest Kubeone (v1.7.3) that doesn't support K8s versions higher than 1.27. https://docs.kubermatic.com/kubeone/v1.7/architecture/compatibility/supported-versions/

**Comment by JKBGIT1** [comment]
https://github.com/berops/claudie/pull/1501
