### ISSUE TITLE
Bug: Neither `refresh-docs` label nor `/refresh-docs` command refreshes the docs

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#1281]
### Current Behaviour
The expectation that either of `refresh-docs` label and `/refresh-docs` command rebuilds the docs. The following PR had it both and docs refresh didn't happen: https://github.com/berops/claudie/pull/1280

### Expected Behaviour
Docs should be rebuilt on either the `refresh-docs` label and `/refresh-docs` command.

### Steps To Reproduce
See the steps in https://github.com/berops/claudie/pull/1280

**Comment by JKBGIT1** [comment]
Hi @bernardhalas , I am afraid this won't work unless this [PR](https://github.com/berops/claudie/pull/1251) is merged.

**Comment by JKBGIT1** [comment]
I'm closing this issue because I tested the `refresh-docs` label and the `/refresh-docs` comment on https://github.com/berops/claudie/pull/1271 after merging https://github.com/berops/claudie/pull/1251 , and everything works.
