### ISSUE TITLE
Bug: terraformer doesn't release lock after an unexpected restart

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1286]
### Current Behaviour

A `builder` got restarted after I applied InputManifest. The InputManifest got stuck in `IN_PROGRESS`, specifically in the Terraformer phase and nothing was going on in the `terraformer`. In an hour a `builder` got restarted again, but this time a `terraformer` also got restarted. This resulted in re-running the workflow and erroring out in `terraformer` with the following logs regarding not released state lock.

```
diagnostic:
        severity: error
        summary: Error acquiring the state lock
        detail: Error message: ConditionalCheckFailedException: The conditional request failed
Lock Info:
  ID:        8b4fdb90-463a-1a74-5da1-523f4fa71cdc
  Path:      claudie-tf-state-files/default-jakub/jakub-fgion0h
  Operation: OperationTypeApply
  Who:       @terraformer-6965b5fbc-cvzn6
  Version:   1.4.4
  Created:   2024-03-21 06:49:42.660346554 +0000 UTC
  Info:      


Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
```

### Expected Behaviour
I assume the `terraformer` should release the lock on the state file after an unexpected restart.

### Steps To Reproduce
Hard to tell, because I don't know why the `builder` restarted at first and I don't know what were the reasons behind the next `builder` and `terraformer` restart.

**Comment by JKBGIT1** [comment]
Maybe one more thing to add. Infrastructure was provisioned by `terraformer` even though the InputManifest got stuck in the `Terraformer` phase.

**Comment by bernardhalas** [comment]
Today at the grooming we agreed that we will limit the scope of this issue to adding an entry into the troubleshooting guide about how to resolve a locked state in Terraformer.
