### ISSUE TITLE
Chore: Resolve networking misleads in Hetzner Claudie tutorial

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1289]
### Description

A user followed the [Claudie Hetzner tutorial](https://community.hetzner.com/tutorials/kubernetes-with-claudie). Based on the blog, he thought Claudie should create a private network in Hetzner Cloud. However, Claudie does not operate this way, and therefore he assumed it was an error (read [more](https://kubernetes.slack.com/archives/C05SW4GKPL3/p1711055451564769?thread_ts=1711034557.059299&cid=C05SW4GKPL3)).

### Exit criteria

- [ ] Correct misleading network information in the Claudie Hetzner blog post

![image](https://github.com/berops/claudie/assets/43497822/6743b0c3-ad5f-4ba4-997e-28368038fd1e)

**Comment by cloudziu** [comment]
PR Merged, but on the site is still the old version: https://community.hetzner.com/tutorials/kubernetes-with-claudie
I will close the task after it will get updated.
