### ISSUE TITLE
Chore: Troubleshooting guides with direct access to MongoDB

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1315]
### Description

Write some paragraphs about the most common scenarios, where modifying the InputManifest record through direct access to MongoDB can help.

### Exit criteria

- [ ] Think about the most common scenarios (resolving ERROR with/without re-running the workflow, ...)
- [ ] Written paragraphs in the [Troubleshooting](https://docs.claudie.io/latest/troubleshooting/troubleshooting/).

EDIT: added first task in the exit criteria

**Comment by miroslavkohutik** [comment]
Should be mostly fixed by #1337

**Comment by Despire** [comment]
No manual access should be needed to MongoDB, if the user needs to manually update some fields it's most likely a bug and needs to be fixed
