### ISSUE TITLE
Bug: The `dsChecksum` wasn't updated on the autoscaling request

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1340]
### Current Behaviour

On the autoscaling request Claudie didn't change the `dsChecksum`, only the `desiredState`. Due to that, the autoscaler didn't work ([see](https://kubernetes.slack.com/archives/C05SW4GKPL3/p1713381901032579)).

According to the logs, the `cluster-autoscaler` failed to retrieve the `resource lock kube-system/cluster-autoscaler` and then lost master. The same error occurrence https://github.com/berops/claudie/issues/1065#issuecomment-2060689986 .

```
$ kubectl logs -n claudie autoscaler-wox01-cluster-qy5w5zl-57f74c7dd5-v8gbd -c cluster-autoscaler -p
...
I0417 18:08:17.383459       1 static_autoscaler.go:673] Decreasing size of compute01-ccx23-auto-fy7ww3o, expected=7 current=6 delta=-1
I0417 18:08:17.383801       1 static_autoscaler.go:426] Some node group target size was fixed, skipping the iteration
I0417 18:08:27.485122       1 static_autoscaler.go:673] Decreasing size of compute01-ccx23-auto-fy7ww3o, expected=7 current=6 delta=-1
I0417 18:08:27.485366       1 static_autoscaler.go:426] Some node group target size was fixed, skipping the iteration
I0417 18:08:28.291313       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0417 18:08:28.292135       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 787.249µs
E0417 18:08:33.691966       1 leaderelection.go:330] error retrieving resource lock kube-system/cluster-autoscaler: Get "https://loadbalancer.worldofpotter.eu:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler": context deadline exceeded
I0417 18:08:33.695145       1 leaderelection.go:283] failed to renew lease kube-system/cluster-autoscaler: timed out waiting for the condition
F0417 18:08:40.377907       1 main.go:578] lost master
```

Besides that, there was an error in the `builder` from 8 days ago. The error was produced by the `ansibler` due to the timeout on static nodes while installing the VPN. However, the InputManifest was in a `DONE` state constantly... (see https://github.com/berops/claudie/issues/1339)

One more thing. The `cluster-autoscaler` states that there are 6 nodes and the expected amount is 7. On the other hand, the InputManifest record in Mongo has 7 autoscaled nodes in the `currentState` and 6 autoscaled nodes in the `desiredState`.

### Expected Behaviour

Claudie should update the value of the `dsChecksum` when it updates the `desiredState`.

### Steps To Reproduce
I don't know.

### Anything else to note
The same error in the `cluster-autoscaler` https://github.com/berops/claudie/issues/1065#issuecomment-2060689986

EDIT: a [workaround](https://kubernetes.slack.com/archives/C05SW4GKPL3/p1713430630300339?thread_ts=1713381901.032579&cid=C05SW4GKPL3) for this error, when it appears.

**Comment by Despire** [comment]
closed by https://github.com/berops/claudie/pull/1498
