### ISSUE TITLE
Inclusion of VPC, Subnet, and IAM Rules in AWS InputManifest

### ISSUE THREAD

**Issue by chaitu7989** [berops/claudie#1418]
I'm currently working on deploying resources on AWS using Claudie and Kubernetes, and I have a few questions regarding the capabilities of the AWS InputManifest:

**VPC and Subnet**:  Is it possible to include specifications for VPC and subnet directly within the AWS InputManifest? If so, could you please provide guidance on how to do this effectively?

**IAM Rules**:  Similarly, I'm curious about incorporating IAM rules directly into the AWS InputManifest. Is there a recommended approach for including IAM role specifications within the manifest?

**Inputmanifest**:-
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: AWSExampleManifest
  labels:
    app.kubernetes.io/part-of: claudie
spec:

  providers:
    - name: aws-1
      providerType: aws
      secretRef:
        name: aws-secret-1
        namespace: mynamespace

  nodePools:
    dynamic:
      - name: control-aws
        providerSpec:
          # Name of the provider instance.
          name: aws-1
          # Region of the nodepool.
          region: eu-central-1
          # Availability zone of the nodepool.
          zone: eu-central-1a
        count: 1
        # Instance type name.
        serverType: t3.medium
        # AMI ID of the image.
        # Make sure to update it according to the region. 
        image: ami-0965bd5ba4d59211c

      - name: compute-1-aws
        providerSpec:
          # Name of the provider instance.
          name: aws-1
          # Region of the nodepool.
          region: eu-central-2
          # Availability zone of the nodepool.
          zone: eu-central-2a
        count: 2
        # Instance type name.
        serverType: t3.medium
        # AMI ID of the image.
        # Make sure to update it according to the region. 
        image: ami-0e4d1886bf4bb88d5
        storageDiskSize: 50

      - name: compute-2-aws
        providerSpec:
          # Name of the provider instance.
          name: aws-1
          # Region of the nodepool.
          region: eu-central-2
          # Availability zone of the nodepool.
          zone: eu-central-2a
        count: 2
        # Instance type name.
        serverType: t3.medium
        # AMI ID of the image.
        # Make sure to update it according to the region. 
        image: ami-0965bd5ba4d59211c
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: aws-cluster
        version: v1.27.0
        network: 192.168.2.0/24
        pools:
          control:
            - control-aws
          compute:
            - compute-1-aws
            - compute-2-aws
        vpc:
          id: vpc-xxxxxxxx  # Replace with your VPC ID
          subnets:
            - subnet-xxxxxxxx  # Replace with your Subnet ID
          securityGroups:
            - sg-xxxxxxxx  # Replace with your Security Group ID
        iamRoles:
          instanceRole: arn:aws:iam::123456789012:role/InstanceRole  # Replace with your Instance Role ARN
          nodeRole: arn:aws:iam::123456789012:role/NodeRole  # Replace with your Node Role ARN

Ensuring that VPC, subnet, and IAM rules are correctly configured is crucial for our deployment requirements. Any insights or best practices you can provide on these matters would be greatly appreciated.

Thank you for your assistance!

**Comment by bernardhalas** [comment]
This is now possible thanks to the new release: https://github.com/berops/claudie/releases/tag/v0.9.0
The recommended way would be to customize the TF templates and build the nodepool configuration based on these custom templates.
