### ISSUE TITLE
Feature: Ditch ubuntu for TalOS

### ISSUE THREAD

**Issue by caniko** [berops/claudie#1580]
### Motivation
Using genralized images to maintain k8 increases complexity without much benefit.

Immediate benefits:
- Ease of adding and changing kernel modules
- Rolling upgrades without service disruption

### Description
Every node that can have its OS coerced should be TalOS based for ease of use an maintainability.

**Comment by bernardhalas** [comment]
Related to: https://github.com/berops/claudie/issues/1231
There are more aspects to using custom OSs or OS images as well (security, speed, ease of use). Talos would definitely be one of the options.

Our current priority is to polish the provisioning and autoscaling workflows. Once done, we'll look at the OS used on the nodes. Closing this issue in favor of the broader #1231.
