### ISSUE TITLE
Use claudie.io domain for load-balancer endpoint

### ISSUE THREAD

**Issue by jaskeerat789** [Berops/claudie#162]
# Description
For dev purposes, we were using jaskeerat.ninja domain for LB feature. I think it's time to port to claudie.io now. jaskeerat.ninja was free domain and is going to expire in like 2 months. 

@bernardhalas I can help you with this.

**Comment by MarioUhrik** [comment]
We can also temporarily leave `claudie.io` as it is, and instead rent some other domain to use for E2E tests.

**Comment by bernardhalas** [comment]
The `claudie.io` domain has been migrated via https://github.com/Berops/infra/pull/195
Probably there's some work left to be done in the E2E test configuration, correct?

**Comment by MarioUhrik** [comment]
Yes, we have a little bit of work left to be done, I assume.
- perhaps delegate a subzone of `claudie.io` to E2E LB testing (and move it to `platform`)
- update `test-sets` to use the new hostname
- update E2E secrets to point to the new zone
This can be closed when `jaskeerat.ninja` isn't used anywhere in the E2E tests
