### ISSUE TITLE
Feature: Production readiness of Minio

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#182]
### Motivation:

Currently, Minio is deployed in very simplistic fashion. We are using single replica minio with a single PV backing it. This is fine for dev environment but not for the production.

### Description:

Minio deployment should be production ready, meanining implementing/reviewing
- 3-replica setup
- Multiple PVs/drives backing it
- #179 
- #178 

### Exit criteria:
- [ ] The Minio is deployed in 3-replica set up
- [ ] The Minio has more than just 1 PV backing it
- [ ] #179 is reviewed and possibly implemented (not in MVP)
- [ ] #178 is reviewed and possibly implemented (not in MVP)

**Comment by bernardhalas** [comment]
Grooming outcome: Let's investigate how much of an effort would it be to implement:
- The Minio is deployed in 3-replica set up
- The Minio has more than just 1 PV backing it

After we have a better glimpse of the expected effort, let's re-assess.

**Comment by MarioUhrik** [comment]
If we're going to do the above, we should consider doing the same for the other data stores - mongoDB and dynamoDB

**Comment by MarioUhrik** [comment]
I think that mongoDB and dynamoDB are fine for now, and if a true need arises later, we can make them into a multi-replica setup as well
