### ISSUE TITLE
Security hardening of firewall rules of Claudie-made clusters

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#205]
Within https://github.com/Berops/platform/tree/master/services/terraformer/templates, we could significantly improve security of the Claudie-made clusters by closing unnecessary ports from unnecessary IP ranges.

- Do we really need to use source IP range `0.0.0.0/0`, or can we narrow it down, e.g. to the Wireguardian CIDR?
- Close the protocol/ports that aren't needed (e.g. here we currently allow all TCP ports: https://github.com/Berops/platform/blob/master/services/terraformer/templates/gcp-lb.tpl#L33)

**Comment by jaskeerat789** [comment]
Currently being worked in #306 so might be outdated

**Comment by MarioUhrik** [comment]
We're leaving ICMP open, the above PR is merged
