### ISSUE TITLE
Feature: Add support for a new cloud provider with a free tier

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#235]
It would be nice if Claudie had support for another public cloud provider besides GCP, which also offers some sort of "free credits".
This way, people can try Claudie out with a real multi-cloud cluster for free.

- choose a cloud provider that easily offers free credits, ideally a popular one
- implement it
- appropriately extend the docs, the test sets, and everything else

**Comment by MiroslavRepka** [comment]
After #334 is merged, Claudie will now support GCP, Hetzner, AWS, Azure and OCI. All of them offer some sort of a free tier, thus I would close this issue one the mentioned PR is merged.
