### ISSUE TITLE
Feature: Replace `%v` for `%w` when returning an error

### ISSUE THREAD

**Issue by MiroslavRepka** [Berops/claudie#274]
### Motivation:

As @Despire pointed out, we are using `%v` when returning an error in our codebase. However, we should really use `%w`, since it wraps an error and can be later unwrapped, which is used in the `errors.Is()` function. See the discussion [here](https://github.com/Berops/claudie/pull/271#discussion_r965805489) and more concise explanation [here](https://stackoverflow.com/questions/61283248/format-errors-in-go-s-v-or-w)

### Description:

Review the use of `%v` formatter and replace it with `%w` where appropriate. 

### Exit criteria:
- [x] Replace `%v` for `%w` where needed
- [ ] See if we can leverage the `%w` formatter in all services

**Comment by Despire** [comment]
Resolved by #292
