### ISSUE TITLE
Proposal: Modify the `.tpl` files

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#295]
### Motivation:

The way, we define the infra in terraform is kind of clumsy at the moment. We define the K8s and LB node pools similarly, however, we use 2 different `.tpl` (`<provider>.tpl` and `<provider>-lb.tpl` ) files for them and in each, we define a VPC, subnet, firewall and node specification. 

I propose to change the way we use `.tpl` files to become more flexible. 

We can define two templates per provider, one for node pool definition and one for networking. 
- the node pool definition would only define the instances (VMs) + ssh keys if supported
- the networking definition would define a VPC, subnet and firewall rules

This would give us flexibility when defining the networking side of things (firewall rules) while lifting the burden of maintaining 2, similar files.

In the end, each provider would have 
- `<provider>-node.tpl`  for node pool definition of K8s and LB nodes
- `<provider>-networking.tpl` for networking definition for K8s and LB nodes

### Description:

The `.tpl` files would be modified to implement the proposed way of structuring terraform code.

### Exit criteria:
- [ ] The new `.tpl` files were designed
- [ ] The new `.tpl` files were tested

**Comment by Despire** [comment]
Was never groomed
