### ISSUE TITLE
Observe reasonable (financial) scalability limits of the platform

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#300]
### Motivation:
Many public cloud providers charge for the egress traffic. As Claudie is used for creating multi-cloud clusters, there will always be some egress traffic between the public cloud providers. Let's find out the reasonable limits of Claudie deployments considering the potential networking bill. By reasonable limits (subject to a discussion), we can consider a situation when the egress costs would reach the costs for compute and storage combined.

### Description:
There's an expectation that the cluster network traffic grows with the following factors:
- workload traffic
- velocity of state changes in the cluster (pod status updates, endpoint updates,...)
- number of state checks in the clusters (controllers updating CRDs)
- number of nodes in the cluster

While some of the above items are outside of our area of control, we should at least be able setting an upper recommendation purely by observing the contribution of the count of nodes as a factor and state changes as another one.

There's close to no difference in K8s traffic overhead per node based on the hosting public cloud provider. This should probably be verified, the only provider-aware component of the stack is Longhorn.

Considering the above statement confirmed, we can run the test by deploying a Claudie cluster within a single provider. We play the test scenarios in a few modifications and we'll try to extrapolate the egress traffic as:
- function of the node count
- function of state change in the cluster (e.g. pods updated)

From the traffic volumes we can easily get to the egress costs. The traffic volumes can be easily collected by the raw interface counters (there's a ton of tools for this).

### Exit criteria:
- [ ] Propose test scenario
- [ ] Execute the test scenario
- [ ] Analyse and present the results

**Comment by MarioUhrik** [comment]
Please check whether there are any blog posts/papers on this.
I find it very likely that similar experiments have already been done

**Comment by MarioUhrik** [comment]
This might result in a nice blog post
