### ISSUE TITLE
Feature: Create subnet per region

### ISSUE THREAD

**Issue by MiroslavRepka** [Berops/claudie#310]
### Motivation:

While working on AWS support, I found out that VMs from region A cannot join a subnet in region B. Therefore, currently, we only support one region for the node pools in AWS, (which might be true for other providers as well). If we want to support multiple regions per provider, we need to create a subnet based on the region and assign it to the particular node pool.

### Description:

Subnets should be dynamically created per region so that we have 1 VCN and N subnets for N regions where we have current node pools. Node pools should be also assigned to the correct subnet.

### Exit criteria:
- [ ] Create an algorithm which will identify used regions and creates one subnet per region
- [ ] Assign node pools to the correct subnet

**Comment by MarioUhrik** [comment]
Most likely we should just give a separate subnet to each claudie nodepool
