### ISSUE TITLE
Feature: Use cache for terraform providers

### ISSUE THREAD

**Issue by MiroslavRepka** [Berops/claudie#312]
### Motivation:

The Claudie workflow is starting to be kind of slow, now that we added new cloud providers. In order to optimize it, we should look at more than just a code structure. 

When I was monitoring Claudie, it dawned on me that every time we call `terraform init` in Terraformer, it downloads the used providers, since the working directory does not contain `.terraform`,[ (which is used as a cache for the providers)](https://www.terraform.io/cli/init#working-directory-contents). We can improve this by creating `.terraform` and copying the cached providers. This would shave off ~15s for each `terraform init` (there is usually one per lb/k8s cluster and DNS).

### Description:

When creating terraform files, we should also create a `.terraform` directory and copy the cached providers there to speed up the `terraform init` phase.

### Exit criteria:
- [ ] The cache for used providers is defined somewhere in Terraformer
- [ ] The providers are copied into the `.terraform` directory when we are initialising the terraform

**Comment by MiroslavRepka** [comment]
After some trial and error, the issue does not look as simple as it would seem. To avoid wasting more time on this rn, I am moving this issue to backlog. For anyone who will pick up this issue, see #358

**Comment by MarioUhrik** [comment]
If we don't come back to this before 2023, I'd consider closing it

**Comment by MarioUhrik** [comment]
Ungroomed, to be considered for deprioritization and closing

**Comment by Despire** [comment]
Closing this due to low priority atm, related PR #358
