### ISSUE TITLE
Produce a short prerecorded intro demo of Claudie

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#350]
We should start making some promo material for Claudie. 
We can start with a short prerecorded introduction video of what Claudie does, how, and why.

- up to around 5 minutes long
- the why, the what, the how
- heavily scripted audiovisuals
- possibility to hire a voice actor

This one might be useful as a quick introduction video, and as a "basis" for future demos/webinars.

Child issue of https://github.com/Berops/claudie/issues/146

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
animation work has been concluded.
we should probably decide on where and how to publish the video.

**Comment by MarioUhrik** [comment]
The video is done - we'll upload it on Youtube, probably embed the Youtube link into the README, and we can close the issue

**Comment by MarioUhrik** [comment]
https://www.youtube.com/watch?v=q4xdAiHYxZQ&ab_channel=berops
