### ISSUE TITLE
Use Golang Terraform API in place of Terraformer shell calls

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#36]
**Motivation**
At the moment, we're calling Terraform via Shell, but there exists a Golang-native API for Terraform.
Using that instead could be cleaner.

**Description**
Refactor all usages of Terraform shell calls into using a Golang-native API for Terraform.

**Exit Criteria**
- [ ] All usages of Terraform shell calls are refactored into using a Golang-native API for Terraform

**Comment by jaskeerat789** [comment]
not a priority anymore
