### ISSUE TITLE
Build multi-arch container images in CI

### ISSUE THREAD

**Issue by jaskeerat789** [Berops/claudie#366]
### Motivation:
After having a discussion in the Slack channel, the team was convinced that we want to support `arm64` arch along with currently supported `amd64` arch. This makes sense since the popularity of arm based personal machine are becoming popular and the end users might want to run claudie locally on these arm64 machines. 
We can use the official docker plugin [`buildx`](https://github.com/docker/buildx) and pass list of archs that we want to support.

### Exit criteria:
- [ ] build multi-arch images in CI

**Comment by MarioUhrik** [comment]
Please check whether this GitHub Action is of any help
https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
