### ISSUE TITLE
Feature: Open ports on k8s-cluster after LB deletion

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#373]
### Motivation:

After detaching Load-Balancers from a k8s-cluster the only ports that are accessible from outside the k8s-cluster are `[22, 5180, icmp, 6443 (if no LB ApiServer exists)]`
### Description:

As originally part of issue #307, Come up with a workflow that would expose the `target_port` from the destroyed Load-Balancers on the nodes directly, as detaching the LB would prevent any communication from outside the k8s-cluster
(This could potentionally include extending the manifest to support ports that should be opened)
### Exit criteria:
- [ ] Come up with a workflow to open up ports on the Nodes directly after detaching the Load-Balancers
- [ ] Validate the workflow for correctness.

**Comment by MarioUhrik** [comment]
We've agreed that If someone wants to expose a Nodeport, they will need to make an LB for it.
We'll probably ignore this gap for the time being, until motivated otherwise.
