### ISSUE TITLE
Use the Golang KubeOne API instead KubeOne shell calls

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#38]
**Motivation**
At the moment, we're calling KubeOne via Shell, but there may exist a Golang-native API.
Using that instead could be cleaner.

**Description**
Refactor all usages of KubeOne shell calls into using a Golang-native API for KubeOne.

**Exit Criteria**
- [ ] All usages of KubeOne shell calls are refactored into using a Golang-native API for KubeOne

**Comment by jaskeerat789** [comment]
not a priority anymore
