### ISSUE TITLE
Adjust timeouts in `testing-framework`

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#384]
Recently, E2E tests have been failing due to hitting the timeout for Longhorn.
We suspect that the timeout may be far too low.

Please review this timeout and increase it, if possible.
It would be worth checking all other timeouts inside `testing-framework` as well.

**Comment by Despire** [comment]
I've actually just doubled the time for longhor in this [PR](https://github.com/Berops/claudie/pull/378/commits/22eaa3eb5907eb2d2cceef7531026cfb7418afd4), as every CI run failed on this.

**Comment by MarioUhrik** [comment]
Cool @Despire, could you please close this issue if you confirm it's fine ?

**Comment by Despire** [comment]
Closing, resolved in #378
