### ISSUE TITLE
Improve API endpoint change ansible task

### ISSUE THREAD

**Issue by jaskeerat789** [Berops/claudie#385]
### Motivation:
In the latest PR regarding  LB delete/updation (#371), we observed that the API endpoint changing in ansible playbook depends on the last used endpoint URL. This creates a problem when we try to swap API server LB. Instead of deleting the existing LB cluster and attaching the new LB cluster, we have to change the API-server from old LB endpoint to one of the IP of control node and then change it to new LB endpoint.

```css
"Swapping old API server LB with new one"

Old LB endpoint -> control node IP -> New LB endpoint 

"Instead of moving from old endpoint to new endpoint directly"
Old LB endpoint -> New LB endpoint

**Comment by Despire** [comment]
closed by #371
