### ISSUE TITLE
Terraformer timeouts when provisioning Azure VMs

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#386]
```
Code="OSProvisioningTimedOut" Message="OS Provisioning for VM 'ts1-azure-8yuszmh-azure-compute-2' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. For details on how to check current provisioning state of Windows VMs, refer to https://aka.ms/WindowsVMLifecycle and Linux VMs, refer to https://aka.ms/LinuxVMLifecycle."
```
This happens e.g. after 20 minutes of Terraform waiting for Azure to return the "success" signal.
I don't think this is a problem on the Terraform level though, because the timeout in Terraform is 60 minutes.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#timeouts

This error spawns a lot of other errors. Terraform doesn't know the VM is successfully provisioned in the end, tries to create it, but fails.

At the moment, this seems quite common in our E2E pipelines, causing failures.

**Comment by Despire** [comment]
closing this issue as it was not been seen since updating the images to ubuntu 22.04, if this issue arises again updating the image to the latest version should be tried first to resolve it.
