### ISSUE TITLE
Bug: infra gets deleted after config is reapplied with errors

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#402]
### Current Behavior:

After applying a config successfully  and making a modification to it that doesn't pass through the validation stage in the frontend service the infra of the previously created config gets deleted
### Expected Behavior:

A deletion of the infra shouldn't happen, if new changes to the config are invalid the old infra shouldn't be changed
### Steps To Reproduce:

1. apply config
2. make a change that will fail on the validation stage in the frontend service
3. See terraformer logs for deletion of the infra

**Comment by MiroslavRepka** [comment]
>the infra of the previously created config gets deleted

Does this mean that the error in validation will somehow trigger the deletion process?

**Comment by Despire** [comment]
> Does this mean that the error in validation will somehow trigger the deletion process?
Yes

**Comment by Despire** [comment]
it's a simple fix by just checking if the config had invalid manifest [here](https://github.com/Berops/claudie/blob/master/services/frontend/process_configs.go#L107-L122)
