### ISSUE TITLE
Input validation - name length & characters

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#415]
If the name of LB/K8s cluster is too long, or contains strange characters, the process might fail.
We should guard this at the input validation level, if we aren't yet.

**Comment by MiroslavRepka** [comment]
The validation is already implemented on frontend level.

However, we decided to shorten the name from `<clusterName>-<clusterHash>-<nodepoolName>-<index>` to  `<nodepoolName>-<index>`. This change would be implemented via `hostaname` in kubeone manifest. 
NOTE: change `validateFutureDomain()` check
