### ISSUE TITLE
Improve HA of Longhorn PVs via node labels

### ISSUE THREAD

**Issue by cloudziu** [Berops/claudie#425]
### Motivation:

Currently, Longhorn PV data is replicated with complete disregard to zone/region/provider.
In order to have more "HA" storage, we can provide Longhorn with the necessary information to schedule replica placements better.

### Description:

Longhorn when scheduling PVC replication, lookups [Kubernetes well-known labels](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion) `topology.kubernetes.io/zone`. Nodes that don’t belong to any zone will be treated as if they belong to the same zone. More info on [Longhorn scheduling policy](https://longhorn.io/docs/archives/1.0.1/volumes-and-nodes/scheduling/#scheduling-policy). To leverage its capabilities - of maintaining replicas in different zones, Kubernetes Nodes should have labels with their respective zone. 
We propose the following labels.

Hetzner Node:
```
topology.kubernetes.io/zone: fcs1
topology.kubernetes.io/region: eu-central
claudie.io/cloudprovider: hetzner
```

AWS Node:
```
topology.kubernetes.io/zone: us-east-1c
topology.kubernetes.io/region: us-east-1
claudie.io/cloudprovider: aws
```

### Exit criteria:
- [x] Nodes are now labeled as suggested
- [ ] We've experimentally ensured that Longhorn tries to spread replicas across zones

**Comment by cloudziu** [comment]
Hi @MarioUhrik, thank for your input. 
The way I thought it would look like: 
Labels have only their atomic values. If we want to add additional information, it would be added in different labels. In case there are already described in [well-known labels](https://kubernetes.io/docs/reference/labels-annotations-taints/,) we should use them. Otherwise, I suggest to extend with Claudie specific labels. 
Example: if we want to add cloud provider/zone/region information:
Hetzner Node:
`topology.kubernetes.io/zone: fcs1`
`topology.kubernetes.io/region: eu-central`
`claudie.io/cloudprovider: hetzner`

AWS Node:
`topology.kubernetes.io/zone: us-east-1c`
`topology.kubernetes.io/region: us-east-1 `
`claudie.io/cloudprovider: aws`

**Comment by cloudziu** [comment]
This will probably be useful - collecting cloud instance metadata via IMDS (instance metadata service): [OCI](https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.html), [AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html), [Azure](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux), [GCP](https://cloud.google.com/compute/docs/metadata/querying-metadata)

**Comment by MiroslavRepka** [comment]
>Currently, Longhorn PV data is replicated with complete disregard to zone/region/provider

This sentence is not true though. While I agree with the proposed feature, it's more like an update of the current one rather than a new one. We annotate all nodes based on their provider, as described in the docs [here](https://github.com/Berops/claudie/blob/feat/update-azure-docs/docs/storage/storage-solution.md#example). We use `node.longhorn.io/default-node-tags` annotation, which at the time was the correct approach. 

However, I am all for the proposed feature, I just wanted to clarify this :).

**Comment by MiroslavRepka** [comment]
After PR #543 the longhorn now replicates PVs from the default storage class (`longhorn`) across multiple nodes in different zones.
