### ISSUE TITLE
Explore the limits of how far apart etcd members can be

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#427]
@cloudziu has recently done a bunch of very interesting benchmarks of ETCD performance in various multi-cloud & multi-region setups.

I think it would be useful if we experimentally explored questions such as:
- how far apart geographically can ETCD members be, and still work fine?
- is it a good idea to make an ETCD cluster out of 3 different cloud providers within the same region?
- etc.

I think this would help us answer a lot of burning questions surrounding Claudie, and it would result in a very interesting blog post.
The blog post could consist of multiple experiments and their results, and then some conclusions.
In the future, it could be referenced each time someone would have any questions regarding this topic.
Perhaps it might be worth adding into `/docs` as well.

**Comment by jaskeerat789** [comment]
Maybe we should check the official docs from k8s.io on this. We can treat it as a reference.

**Comment by MiroslavRepka** [comment]
The issue will be closed once the blog is published.

**Comment by cloudziu** [comment]
As today the blog post has been published, we agreed to close this issue.
