### ISSUE TITLE
Stable releases

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#438]
If someone visits the Claudie GitHub page today, they might see that the latest build is failing.
That's fine, that happens. 

But we need to start making "official releases", so that people always have a stable version to go to.
E.g. something like this would be nice 
https://github.com/actions-runner-controller/actions-runner-controller/releases/tag/actions-runner-controller-0.21.1

I think the release should contain the manifests for that version, excluding testing framework.
The manifests should be pinned to a particular image tag.

We must ensure that the image tag stays in the repository permanently.

DockerHub retention policy update: https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/
![image](https://user-images.githubusercontent.com/61180606/205300673-498288e2-f6a5-4cdd-91b0-baf0f3434657.png)

**Comment by cloudziu** [comment]
Hey Mario,
I would like to mention few things
Releases should contain some kind of patch notes:
 - new features
 - bugfixes
 - known issues

Also if a new version is released - it should provide an "Upgrade Guide" - IMO its crucial

The manner of versioning you've shown as example is Semantic Versioning. I think that, there are many tools that help integrating such flow with GH repositories. For example, I used [this](https://gitversion.net) before for automatic versioning.

**Comment by Despire** [comment]
https://goreleaser.com/
Could be relevant for this issue

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> We must ensure that the image tag stays in the repository permanently.

this ^ has at least 3 solutions I can think of:
* store the images in a self-hosted container repository (harbor et al.)
* get DH's pro plan with fewer restrictions
* switch to a container repository (such as GHCR)

another way to look at it is we could devise a release schedule and make it clear that only *x* latest (major/minor) releases are supported from our side.
example:
> Releases newer than `0.x.*` are fully supported for at least 6 months.

---
I agree with @cloudziu that every release should include release notes of sorts (changelog.md?). they could also be written (at least) partially by hand but added to the release page automatically as part of an Actions `release` workflow (not pasted manually).

autogenerated release notes could be had if we agreed on adhering to a particular commit message style that could then be parsed into sections of "Bug fixes" and "Enhancements" by tools in an automated fashion, making the release process a no-brainer and a thing that can be done often without pain.

**Comment by MiroslavRepka** [comment]
Release workflow has been added in #491, including a small [how to](https://github.com/Berops/claudie/blob/master/docs/contributing/release.md). I would consider this issue completed after the first official release is published.
