### ISSUE TITLE
Feed cluster creation status into frontend

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#440]
We've received complaints that without prior experience with Claudie, it's difficult to know what's happening, whether everything is going well, and how long it should the user keep waiting.

I propose we start feeding "status updates" into Frontend somehow.
For example, a periodic GRPC call to Context box (or whatever makes sense).
At first, relaying these status updates into the Front logs might suffice.
Later, we'll be ready to display this information via a GUI, shall that be agreed upon as the path to take.

Proposed example, to help illustrate my thoughts:
```
$ kubectl -n claudie logs frontend -c frontend -f
10:45 inputManifest.yaml found by k8s_sidecar
10:46 inputManifest.yaml sent into context_box
10:47 Creating desired state for MyInputManifest...
10:47 Finished computing desired state for MyInputManifest
10:48 Creating infrastructure for MyInputManifest via Terraformer...
10:53 Creating infrastructure for MyInputManifest via Terraformer...
10:58 Creating infrastructure for MyInputManifest via Terraformer...
11:00 Finished creating infrastructure for MyInputManifest via Terraformer.
11:00 Creating VPN for MyInputManifest via Ansibler...
11:05 Creating VPN for MyInputManifest via Ansibler...
11:07 Finished creating VPN for MyInputManifest via Ansibler.
11:07 Creating Kubernetes cluster myCluster1 of MyInputManifest via Kube-eleven...
11:07 Creating Kubernetes cluster myCluster2 of MyInputManifest via Kube-eleven...
11:12 Creating Kubernetes cluster myCluster1 of MyInputManifest via Kube-eleven...
11:12 Creating Kubernetes cluster myCluster2 of MyInputManifest via Kube-eleven...
11:17 Creating Kubernetes cluster myCluster1 of MyInputManifest via Kube-eleven...
11:17 Creating Kubernetes cluster myCluster2 of MyInputManifest via Kube-eleven...
11:19 Finished creating Kubernetes cluster myCluster1 of MyInputManifest via Kube-eleven.
11:19 Finished creating Kubernetes cluster myCluster2 of MyInputManifest via Kube-eleven.
11:19 Provisioning Kubernetes cluster myCluster1 of MyInputManifest via Kuber and Ansibler...
11:19 Provisioning Kubernetes cluster myCluster2 of MyInputManifest via Kuber and Ansibler...
11:21 Finished provisioning Kubernetes cluster myCluster1 of MyInputManifest via Kuber and Ansibler.
11:21 Finished provisioning Kubernetes cluster myCluster2 of MyInputManifest via Kuber and Ansibler.
11:21 Kubeconfig for myCluster1 of MyInputManifest is now available as Kubernetes Secret ${kubeconfig1_secret_name}. Happy kubing!
11:21 Kubeconfig for myCluster2 of MyInputManifest is now available as Kubernetes Secret ${kubeconfig2_secret_name}. Happy kubing!
```

**Comment by MarioUhrik** [comment]
We like the idea of the feature itself, but we need to think about how to implement this from the inter-dependency point of view, so as not to product too much spaghetti code, and not have too many dependencies from one microservice to another.

**Comment by Despire** [comment]
Idea: We could introduce a `WorkflowState` (This would Replace the Error field in database) that would contain 2 values
```go
type Stage string
const (
 Terraformer Stage = "..."
 Ansibler Stage = "..."
 ...
)

type WorkflowState struct {
 Stage Stage
 Error error
}
```

This would be stored in MongoDB where frontend would pull this value from context-box in some interval and display the values in the frontend service in more readable form

This values would be updated by the builder service, after every completed step it would call context-box to update the state. e.g. after terraformer finishes builder makes a call to context-box to update the state.

Since context-box is the only service that has access to the DB it could also have states when scheduler picks-up or stores the config, and same for builder

Thoughts ? @MiroslavRepka

**Comment by MiroslavRepka** [comment]
I like the idea and the implementation, I had a similar one in my head for a while now :). However, there are a few states for each service, i.e. in Ansible `Setting up the VPN`, or `Setting up the Loadbalancers`, etc for each Input manifest. These states might be even more granular, i.e. on per cluster bases, like  `Setting up the VPN for Cluster1` and `VPN has been set up for Cluster2`. This might get tricky to manage, especially when an error occurs, although it depends on how much information we want to pass on to the user. 

Overall I think this is the right direction. :)
