### ISSUE TITLE
Error while cleaning lock in DynamoDB after infra deletion

### ISSUE THREAD

**Issue by jaskeerat789** [Berops/claudie#443]
### Current Behavior:
After deleting the infra, terraformer tries to delete the `lock` from DynamoDB but it fails with the following error:
>  Failed to destroy the infra for project TestSet-2 : failed to remove state lock file ts2-lb-2-s8u3l79 : operation error DynamoDB: DeleteItem, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed 

This error is pretty consistent in CI.

**Comment by Despire** [comment]
closed in #449
