### ISSUE TITLE
Feature: Exponential timeout

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#462]
### Motivation:

Networking issues are common, traffic getting lost, slow connections etc... We should switch to exponential timeout that cancels at 5 min.

Make the timeout exponential with a hard limit between ~5-10 min

### Exit criteria:
- [ ] Implement exponential backoff with a hard limit between 5-10 min

**Comment by bernardhalas** [comment]
Very good topic @Despire . I'd like to throw in an idea - any other than exponential back-off algorithm all the way? This way our concern would be just the initial delay + retry count.

**Comment by Despire** [comment]
I was thinking maybe we could use this library https://github.com/cenkalti/backoff
already has constant, exponential backoff implemented less work on our side.
