### ISSUE TITLE
Certified Kubernetes Conformance

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#463]
Consider getting Claudie CNCF-certified.
This would be an interesting marketing move.
It shouldn't be very hard to pass, since we're just using KubeOne under the hood, which is already certified.

Child of https://github.com/Berops/claudie/issues/146

**Comment by cloudziu** [comment]
1. Requirements and guide lines from [k8s repo.](https://github.com/cncf/k8s-conformance/blob/master/terms-conditions/Certified_Kubernetes_Terms.md)
2. Instructions how to [run tests.](https://github.com/cncf/k8s-conformance/blob/master/instructions.md)

**Comment by samuelstolicny** [comment]
If we want to get k8s conformance certified we have to be a member of CNCF or pay the fee. The fee is the same as the price of joining CNCF. I think it is better to join CNCF when it is the same price.

> What is the cost of certification?
For [members](https://www.cncf.io/about/members/) of the Cloud Native Computing Foundation, there is no charge for certification. There is also no charge for non-profit organizations. For commercial organizations that wish to certify but don't want to become a CNCF member, the fee is the same as [joining](https://www.cncf.io/about/join/) the CNCF.

**Comment by samuelstolicny** [comment]
The price of joining CNCF depends on the type and size of your organization. According to their website[1](https://www.cncf.io/about/join/), here are some examples of the membership prices:

**Academic / Nonprofit:** Limited to academic and nonprofit institutions. $1,000 / $500 annually

**Silver:** Organizations that sell cloud native technologies built on, or integrated with, CNCF projects. The price varies based on the number of consolidated employees. For example, 5,000 employees + $50,000; 3,000 – 4,999 employees $40,000; 1,000 – 2,999 employees $30,000; 500 – 999 employees $20,000; 100 – 499 employees $10,000; Less than 100 employees $5,000

**Gold:** Organizations that sell cloud native technologies built on, or integrated with, CNCF projects. The price is based on a percentage of revenue. For example, $500M+ revenue 0.05%; $100M – $499M revenue 0.075%; Less than $100M revenue 0.1%

**Platinum:** Organizations that sell cloud native technologies built on, or integrated with, CNCF projects. The price is based on a percentage of revenue. For example, $10B+ revenue 0.01%; $1B – $9.9B revenue 0.015%; Less than $1B revenue 0.02%
If you are an end user member who uses cloud native technologies internally but does not sell any cloud native services externally, you can join the End User Community for free[2](https://www.cncf.io/blog/2022/01/25/getting-started-with-your-cncf-membership/).

We should discuss on the platform grooming if this is the thing we want to do.

**Comment by samuelstolicny** [comment]
We are not pursuing the certificate for now because it requires either CNCF membership or a fee of $5000, which we don’t find worthwhile at this stage. We will reconsider it after we have a successful customer implementation.
