### ISSUE TITLE
Bug: Unauthorized in CI pipeline

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#467]
After not using GCP auth plugin in https://github.com/Berops/claudie/pull/457
The CI can't watch over the deployed services due to unauthorized error

```bash
E1221 08:57:33.979189    1607 reflector.go:140] vendor/k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *unstructured.Unstructured: the server has asked for the client to provide credentials
W1221 08:57:35.011583    1607 reflector.go:424] vendor/k8s.io/client-go/tools/watch/informerwatcher.go:146: failed to list *unstructured.Unstructured: Unauthorized
```

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
could this regression be solved by a partial revert?

**Comment by Despire** [comment]
The plugin was deprecated and the CI wouldn't work (it just finished with an error that the plugin was deprecated and not supported anymore), that's why it was removed and updated. Reverting it wouldn't fix it
