### ISSUE TITLE
Feature: Arm binaries inside docker images

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#468]
### Description:

When building multi-arch docker images the binaries downloaded inside the images should be of the same arch as the docker image

For example here we always download amd64 binary
https://github.com/Berops/claudie/blob/b7af0962c73bf57d694d521f21422ef688ca18ef/services/kuber/Dockerfile#L4
### Exit criteria:
- [ ] Download binaries based on the arch type

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
does this need to be groomed? this sounds more like a bug fix to me...

**Comment by MarioUhrik** [comment]
Hi @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf,
let's groom all new issues please, unless we are in a huge rush - in which case the grooming can be accelerated via other means
