### ISSUE TITLE
Feature: Process input manifest on per cluster basis for the whole Claudie process, not just for a single service

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#477]
### Motivation:

Currently, when the user inputs a manifest, claudie will process it as a single unit, even if there are N clusters defined in it. Although there is per-cluster processing deployed on almost every service, the issue arises when at least one of the clusters encounters an error. What happens is, that error in a single cluster will stop the processing of the whole input manifest.

Example: 
- The user defines a single input manifest, with three clusters.
- Terraformer will build the first two clusters, but the third one contains an error, i.e. a wrong VM shape.

The whole workflow is now stopped, as there was an error, however, the first two clusters could be good to continue to the next stage.

Furthermore, I saw a few times some clusters just idling in services, while waiting for one, which was still being processed. The time they spend idling could have been used to continue processing.

### Description:

Claudie should process the input manifest on a per-cluster basis.

### Exit criteria:
- [ ] Claudie is able to process input manifest on a per-cluster basis. 

### Note

I had some time to think this through, so here is my high-level concept of handling it.

Instead of passing the whole desired state to the Terraformer, Ansibler, ... we could change their API to accept only a "single cluster" (or any other data regarding a single cluster), which they would process. 

It would be up to the Builder to call those services and handle the concurrent execution of the clusters. Once all clusters would finish processing, either successfully or not, Builder would return. This would assure that Claudie would try to build every cluster regardless of errors in different clusters and it could save time as some clusters can be built faster than others.

**Comment by bernardhalas** [comment]
I see the reasons behind this approach and I like this way forward. Let's consider the same handling for LB clusters as well.
