### ISSUE TITLE
Feature: Shorten the time to build multi-arch images

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#497]
### Motivation:

Waiting ~1h 20 min for the images to build is a bit long, with the CI pipeline taking more than 2 hours to complete,  shortening the building phase of the CI could decrease the time for the CI to complete substantially while also given faster feedback to the changes made in the codebase.

### Description:

When making changes in only a single service the build times are reasonable, around ~10 mins, however, if any source file is changed that is common to all services they all need to be rebuild and the build times are at ~1h. When the E2E tests also fail making a fix for the issue repeats the cycle where the images need to be build waiting another ~1hour before the E2E tests run.
### Exit criteria:
- [ ] Shorten the time for building multi-arch images

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
big thumbs up.

we could explore using `GOARCH` for Go cross-compilation instead of QEMU; most of the stuff going into the images is written in Go anyway. the build artifacts could then be included into their respective images during the multi-arch build stage (using $VARIABLES FTW).
