### ISSUE TITLE
Feature: Use fully qualified registry names in Dockerfiles

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [Berops/claudie#503]
### Motivation:
Currently, the service Dockerfiles use unqualified image names, which is generally not an issue with Docker. However, I recently tried to build an image with Podman/Buildah and that failed the first time I tried to build it (without me changing the Dockerfile or `/etc/containers/registries.conf`) with "image unqualified".

### Description:
I expect to be able to build the images with Podman (`libbuildah`).

### Exit criteria:
- [ ] service image Dockerfiles contain fully qualified registry names
- [ ] consequently, service images build with Podman

**Comment by MarioUhrik** [comment]
I expect this will be resolved shortly via migration to GHCR.

**Comment by MarioUhrik** [comment]
Sorry, I misunderstood this issue at first.
