### ISSUE TITLE
Feature: Add a security policy

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [Berops/claudie#504]
### Motivation:
As of now, the project is missing a security policy, meaning there is no procedure in place in case of a security incident or should a vulnerability be found in Claudie.

### Description:
Add a security policy to the project.
GitHub's [security policy docs](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository).

### Exit criteria:
- [ ] the project has a security policy

**Comment by MarioUhrik** [comment]
Could you please provide links to some example security policies, or even briefly sketch something that would be suitable for us?
This would help accelerate prioritization of this issue.
