### ISSUE TITLE
Bug: shell calls used instead of SDKs

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [berops/claudie#510]
### Current Behavior:
The codebase currently contains numerous cmd exec calls (shell calls), even in places where proper SDK calls could be used (such as in place of `kubectl`). This is a potential security risk.

### Expected Behavior:
The codebase does not contain cmd exec calls, instead, these are swapped out for SDK calls, to the extent feasible.

**Comment by MarioUhrik** [comment]
FYI @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf 
https://github.com/Berops/claudie/issues/36
https://github.com/Berops/claudie/issues/38

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> FYI @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf #36 #38

thanks @MarioUhrik.
