### ISSUE TITLE
Feature: add a Codeowners file

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [Berops/claudie#511]
### Motivation:
As of now, the repository does not contain a [Codeowners file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).

from GitHub's docs:
![image](https://user-images.githubusercontent.com/61180606/212341250-176e4331-16a7-443f-909a-02f48a8e54d8.png)

### Description:
The Codeowners file allows defining policies for pinging specific people automatically when certain files are touched.

### Exit criteria:
- [ ] a Codeowners file exists and is configured

**Comment by MarioUhrik** [comment]
It's likely we won't need this for the time being, but let's talk at the grooming :)

**Comment by bernardhalas** [comment]
I had a proper read here, and I don't see the benefit currently. Opinions?

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
for instance if we want the programmers (out of all the people in the *org*) to always review changes regarding the code, this is an easy way to do it automatically.

other people can still do reviews, it just makes sure that *specific* people are always pinged on PRs (that are not in the draft stage).

a little UX boost, perhaps.

**Comment by MarioUhrik** [comment]
Based on what most of us think, we're not interested in this as of now.
We'll likely close this within the next few days.

**Comment by MiroslavRepka** [comment]
A project of this size does not need a CODEOWNERS file at the moment.
