### ISSUE TITLE
Feature: Automate release notes

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#516]
### Motivation:

Now, that we will have a release workflow, there is one area which we can automate. This is automatically adding/generating release notes. 

### Description:

This issue aims to automate the addition/generation of release notes. 

### Exit criteria:
- [ ] Release notes are added/generated automatically

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
[goreleaser](https://goreleaser.com/customization/release/) is worth a look IMO.
