### ISSUE TITLE
Chore: Unify the naming scheme in input manifest

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#563]
### Description

This issue aims to unify the naming scheme in the input manifest. Currently, we use camelCase (`nodePool`, `providerSpec`), snake_case (`server_type`, `disk_size`) and kebab-case (`targeted-k8s`). We should really choose one and stick with it. 

I propose using camelCase everywhere.

### Exit criteria

- [ ] New naming scheme was chosen and implemented to input manifest
- [ ] Docs have been updated accordingly

**Comment by MarioUhrik** [comment]
Since this is a breaking change, I'd like to prioritize this to get it done sooner rather than later
