### ISSUE TITLE
Chore: Rename packages from `Berops/claudie` to `berops/claudie`

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#586]
### Description

Recently, the GitHub organisation name has been changed to `berops`. It would be nice if we would stay consistent and change the path to packages from `github.com/Berops/claudie` to `github.com/berops/claudie`.

### Exit criteria

- [ ] Rename package and possibly other references to the new org name.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
is it safe to assume that this would involve renaming the module?
