### ISSUE TITLE
Bug: K8s-sidecar sometimes misses deletion of an input manifest secret

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#587]
### Current Behaviour

Sometimes, the `k8s-sidecar` attached to the `frontend`, misses the deletion of a secret containing an input manifest. This causes a huge issue since if users will delete the secret, and k8s-sidecar misses it, they do not have any other way to interact with the claudie for that input manifest.

### Expected Behaviour

The `k8s-sidecar` should not miss any updates regarding the input manifest secret.

### Steps To Reproduce

1. Deploy a Claudie
2. Apply an input manifest
3. Delete the input manifest

(Some repetition of steps 2. and 3. might be needed)

**Comment by MarioUhrik** [comment]
Are we sure that it's the `k8s-sidecar` to blame?
Do we have sufficient proof of this ?

**Comment by MiroslavRepka** [comment]
The last time this happened to me, I checked the logs of the sidecar, there was no indication it recognized the secret deletion. Might be some misconfiguration of the sidecar, I am not sure. In any way, this issue aims to resolve it.

**Comment by MiroslavRepka** [comment]
Might be related?
https://github.com/kiwigrid/k8s-sidecar/issues/267
