### ISSUE TITLE
Chore: Skip queued CI runs

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#592]
### Description
Currently the CI runs for every commit in a feature branch. This is not necessary, we assume it's safe to skip the commits in the queue and run the CI just for the last of them.

### Exit criteria
CI will run the job just for the last commit within the feature/fix branch in case multiple commits are pushed at the same time.

- [ ] Queued commits are skipped by the CI and only the last one is actioned by the CI.

**Comment by MiroslavRepka** [comment]
Closing as not planned

**Comment by bernardhalas** [comment]
The description is incorrect. Also it's understood this is not an urgent problem to solve atm.
