### ISSUE TITLE
Feature: Describe typical use-cases in the docs

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#632]
### Motivation
To help people see Claudie's value quickly, let's describe typical use cases and how Claudie helps in the docs.

### Description
A section in the `/docs` can be considered a good place for this information. The use cases could also be referred to in a top-level view from the README.

### Exit criteria

- [ ] A set of scenarios that Claudie covers is in the  docs
- [ ] List of typical use cases is added to the project README

**Comment by MarioUhrik** [comment]
Please note we already have https://github.com/berops/claudie/blob/master/docs/use-cases/use-cases.md, so the point of this task would be to refactor/expand on that

**Comment by MiroslavRepka** [comment]
As this has been implemented in #634, can we close this issue?
