### ISSUE TITLE
Proposal: add input manifest option to control Longhorn scheduling

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [berops/claudie#650]
Add an option to the input manifest that would control whether master, worker or all nodes are allowed for scheduling Longhorn workloads.

to quote the note:
> // the number of worker nodes should be equal to number of scheduled nodes in longhorn
> // NOTE: by default, master nodes will not be used to schedule pods, however, if this changes the condition will be broken

right now, the assumption is that master nodes are not used to schedule pods.
the idea is to give user control over whether that is so.

another point is that if this is an important part of the application state, we might want to have it in the input manifest as the "source of truth" for possible reconciliation (i.e. if stuff changes by erroneous manual user intervention).

refs:
* https://github.com/berops/claudie/pull/644#discussion_r1142278773
* https://github.com/berops/claudie/blob/915a7e93ab22d09d9b721830ca2c104dd837bf84/services/testing-framework/test_longhorn.go#L71-L75

**Comment by bernardhalas** [comment]
hi @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf , we had a brief discussion on Friday during grooming on exactly this point IIRC and we saw not much value on this.

Could you please beef-up the task description? Perhaps you're seeing something we're not.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> hi @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf , we had a brief discussion on Friday during grooming on exactly this point IIRC and we saw not much value on this.
> 
> Could you please beef-up the task description? Perhaps you're seeing something we're not.

Thanks, I was not aware.
Will complete the description, I just wanted to start tracking it.
Not sure if I'm seeing something you didn't, we'll all see :))

**Comment by MarioUhrik** [comment]
Currently we don't see a use case for this feature
