### ISSUE TITLE
Claudie live demo

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#651]
Prepare a live demo where we migrate (stateful?) workload from AWS to Azure, and then from Azure to Hetzner, all within minutes apart from each other, in one sitting.
The demo should reveal Claudie to the public whilst showcasing its biggest strengths and most common use cases.

Note that the result should be different from https://www.youtube.com/watch?v=q4xdAiHYxZQ&ab_channel=berops.
Whereas that video is a short pre-recorded introduction to Claudie, this is meant to be a repeatable tech demo for live events.

Possibly blocked by https://github.com/berops/claudie/issues/564, see [thread](https://berops.slack.com/archives/C04JSCX9YCB/p1678986053999209)

**Comment by bernardhalas** [comment]
"Pull off the biggest stunt."

**Comment by MiroslavRepka** [comment]
While working on this issue, I found a few limitations which are being addressed in #728. I will resume the work on this once that PR gets merged. All the progress is saved in `claudie-demo` repository.

**Comment by MiroslavRepka** [comment]
Hi @JKBGIT1 , could you please take it over from here? The current context is saved [here](https://github.com/berops/claudie-demo/tree/stateful-migration/stateful-migration), for any additional questions, please ask us in Slack.

**Comment by JKBGIT1** [comment]
Yesterday at the daily we came up to a conclusion, that there will be only one migration (from AWS to Hetzner) and control plane node will not be migrated. This decision was made based on the time complexity of the initial process (took something around two and half hours)

**Comment by JKBGIT1** [comment]
After implementing the things, which we have discussed, everything was tested and was working correctly, even successful migration of data in etcd StatefulSet. IMO the key takeaways regarding time complexity are:

- spin kind cluster and wait until Claudie is ready - 4 minutes
- create cluster in AWS using Claudie - 15 min
  - TF - 4 min
  - Install VPN - 3 min
  - Calling build cluster on Kube-eleven - 6 min
- deploying etcd workload - 4 min until it's ready to use
- migration from AWS to Hetzner - 28 min
  - TF  - ~4 min
  - Ansibler - ~8 min
  - Kube-eleven - ~5 min
  - Kuber - ~9 min

Overall the whole demo showcase takes almost an hour.

**Comment by JKBGIT1** [comment]
@MarioUhrik pointed out, that we can start the demo with AWS claudie cluster already being up and running with etcd. Then we will only have to explain the current state to the people watching and start the migration from AWS to Hetzner with our comments of what's going on behind the scenes.
A scenario like this will reduce the demo time from ~one hour to about half an hour. Personally, I second this scenario, because I was also considering it while finishing up the demo.
