### ISSUE TITLE
YouTube marketing campaign

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#652]
Since we have a nice ad video already uploaded to [YouTube](https://www.youtube.com/watch?v=q4xdAiHYxZQ) - I would consider using it in a marketing campaign. 
While browsing youtube on my company account I have constantly ads that are advertising some IT-related product/tool/service - I really see an opportunity to reach our potential clients there.
Since we are not experienced in marketing, I think this would be a good task for our future employees from that area.

**Comment by bernardhalas** [comment]
I'll throw in some data. We've paid $400 on YouTube ads, targeting EU-based audience. As a result, we had 20K views of the video linked from the README and some traffic on berops.com. The campaign profile stays saved in our ads account for future work and refinement.
