### ISSUE TITLE
Feature: Rework how logger is used

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#655]
### Motivation

Currently, Claudie is using [zerolog](https://github.com/rs/zerolog), which is a great logger. However, the way Claudie is using it could be better. The zerolog is JSON based logger, meaning that is quite easy to filter out logs which you want to see. However, Claudie is putting all relevant information into the `message` field. I believe it would be better, if Claudie would leverage the JSON-based logging more, i.e. instead of messages like 
```json
{"level":"info","module":"ansibler","caller":"claudie/services/ansibler/server/server.go:222","time":1679568028,"message":"Finished workflow for cluster test-cluster project Test-project"}
```
We would do
```json
{"level":"info","module":"ansibler","caller":"claudie/services/ansibler/server/server.go:222","time":1679568028,"message":"Finished workflow", "cluster":  "test-cluster",  "project": "Test-project"}
```
adding more granular fields.

### Description

Logs in the Claudie should consist of more granular JSON logs, instead of putting all information into a single field.

### Exit criteria

- [ ] Logs in Claudie are now reworked

**Comment by MarioUhrik** [comment]
While this is certainly possible, I don't think it's typically strictly better. 
I'd like to understand what's the exact added value on this one

**Comment by MiroslavRepka** [comment]
I can see the value in simplification of the Go code. Instead of doing 
```go
log.Info().Msgf("some message for cluster %s project %s", cluster, project) // -> 1:00PM INF server.go:65 >some message for cluste test-cluster project test-project module=kuber
...
log.Info().Msgf("other message for cluster %s project %s", cluster, project) // -> 1:00PM INF server.go:65 >other message for cluste test-cluster project test-project module=kuber
```
we would define a logger, with fields already appended to every log, thus we would not have to specify those `%s` everywhere.
```go
logger = log.Logger.With().Str("cluster", clusterName).Caller().Logger().With().Str("project", projectName).Caller().Logger()
logger.Info().Msg("some message") // -> 1:00PM INF server.go:65 >some message module=kuber cluster=test-cluster project=test-project
...
logger.Info().Msg("other message") // -> 1:00PM INF server.go:65 >other message module=kuber cluster=test-cluster project=test-project
```
Also, it might help with log aggregation in the future as the information about certain clusters can be filtered from a field, instead of the message.
