### ISSUE TITLE
Chore: Terminate CI on testing-framework error

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#656]
### Description

Currently, CI only terminates on two conditions
- When testing-framework is successfully completed
- On timeout

This means, that if testing-framework fails, CI has to wait, until the timeout occurs. This could be sped up, if CI would terminate on testing-framework failure as well (with error). 

### Exit criteria

- [ ] CI now terminates, when the testing-framework encounters an error.

**Comment by MiroslavRepka** [comment]
I am not sure yet. I have a few vague ideas but I am not convinced of any of them. If you would have a suggestion, do not hesitate to share it :slightly_smiling_face:.

**Comment by bernardhalas** [comment]
Not really, but this opens a topic, of propagating errors (non-recoverable and recoverable) into the frontend components.

**Comment by MarioUhrik** [comment]
I don't think this open such topics.

If I understand it correctly, this is basically just about the CI currently waiting for the testing framework JOB to be in state `Completed`, with a timeout of X hours.
Instead, the `kubectl` command needs to be rewritten to abort on state `Error`

**Comment by MiroslavRepka** [comment]
I agree with @MarioUhrik here. The error propagation to the frontend component is something different. The CI does not care, what is the error. The whole issue just aims to terminate CI if any error at all occurs. That is already visible from the Job status.

**Comment by bernardhalas** [comment]
Thank you for clarification.
