### ISSUE TITLE
Suggestion: Use CDKTF instead of writing Terraform code in .tpl files

### ISSUE THREAD

**Issue by Archisman-Mridha** [berops/claudie#694]
## Motivation
Currently, in the `terraformer` microservice, the terraform code defining infrastructures is being written in .tpl files. This is because, the terraform code has lots of dynamic variables.
Writing Terraform code in .tpl files is pain as it `doesn't give us any autocompletion and type-safety`.

## Suggestion
Rather than writing the terraform code in .tpl files, we can write it in GoLang itself using `CDKTF`. This provides us with both autocompletion and type-safety.

**Comment by MarioUhrik** [comment]
A strong argument against this is that we've been trying to leverage our strong skills with Terraform into having a far easier time managing Terraformer. Whereas none of us have any skills with CDKTF, nor any other libraries or IaC tools.

**Comment by Archisman-Mridha** [comment]
> A strong argument against this is that we've been trying to leverage our strong skills with Terraform into having a far easier time managing Terraformer. Whereas none of us have any skills with CDKTF, nor any other libraries or IaC tools.

You don't need any extra skill. It's just writing Terraform code in GoLang. If somebody knows Terraform and GoLang, they will need 5 minutes to learn everything about CDKTF.
