### ISSUE TITLE
Feature: run ETCD with a separate disk

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#697]
Every change in `control-plane` nodes when a cloud provider doesn't support disk resizing can result in etcd data being lost/corrupted. Adding a separate disk for the etcd data would prevent those kinds of disasters and give us more freedom when altering the Terraform `control-plane` nodes. By default, the etcd database size limit is 2GB [ref](https://etcd.io/docs/v3.5/dev-guide/limit) So even a small disk with hardcoded value would fit into this scenario.

Similar tasks: #641 

### Exit criteria
- [ ]  Kubernetes `control-plane` nodes have a separate disk for storing etcd database

**Comment by MarioUhrik** [comment]
Theoretically, this could be a small SSD disk.
This should leave us with an option to use a cheaper HDD for the OS.

**Comment by bernardhalas** [comment]
Closing as a part of a backlog cleanup. Don't hesitate to reopen if needed.
