### ISSUE TITLE
Feature: Implementing clean architecture for existing microservices

### ISSUE THREAD

**Issue by Archisman-Mridha** [berops/claudie#715]
### Motivation
Currently, the codebase of each microservice has the business logic and the adapter layer (eg: gRPC implementations, mongoDB implementations etc.) coupled together. Decoupling the business logic from the adapter layer for each microservice will improve the codebase's readability, maintainability and scalability.

### Description
For each microservice, there will be a domain folder which will contain the business logic and an adapter folder which will contain the inbound and outbound adapters.

### Exit criteria
Clean architecture should be implemented for these existing microservices -
- [x] frontend
- [x] context-box
- [x] scheduler
- [x] builder
- [x] terraformer
- [x] kuber 
- [x] kube-eleven
- [x] ansibler 
- [ ] autoscaler-adapter

**Comment by Despire** [comment]
Closing this issue as completed as it was agreed the autoscaler will not be refactored.
