### ISSUE TITLE
Chore: Traces of deleted node still present on other machines

### ISSUE THREAD

**Issue by Despire** [berops/claudie#729]
### Description

Traces of a deleted node are still present on other machines. Investigate if the traces contain anything that should be deleted

To check this
1. Build a cluster
2. Remove some random node
3. SSH into other nodes
4. find traces via `grep -ri /`

### Exit criteria

- [ ]  Investigate if the traces contain anything that should be deleted

**Comment by JKBGIT1** [comment]
Closing the Issue, because the only traces were found in `/var/logs` and @Despire said, that those are irrelevant.
