### ISSUE TITLE
Feature: Consider enforcing odd number of nodes for control plane.

### ISSUE THREAD

**Issue by Despire** [berops/claudie#730]
### Motivation

Having an even number of nodes for the control plane is not advised due to how the Raft algorithm works and thus the etcd quorum.

ref: https://etcd.io/docs/v3.3/faq/#what-is-failure-tolerance

### Description

On the validation level of the manifest enforce that the control plane nodes always have an odd number of nodes (even if multiple providers are used for the control plane)

### Exit criteria

- [ ] Validate that the number of control plane nodes are odd.

**Comment by MarioUhrik** [comment]
I appreciate you opening this, but I wonder if this is nearly as straightforward decision.
I am wondering that, perhaps, someone will want to "manually" replace a master by first adding one and then deleting one of the old ones. Or various other scenarios that I can't even think of.

**Comment by Despire** [comment]
>perhaps, someone will want to "manually" replace a master by first adding one and then deleting one of the old ones. Or various other scenarios that I can't even think of.

hm... yes I'd say you are right about this. I think we shouldn't make assumptions about the use-cases by enforcing an odd-number of nodes.

I'd would close this issue if that's ok @MarioUhrik
