### ISSUE TITLE
Feature: support for external s3, dynamodb and mongodb

### ISSUE THREAD

**Issue by katapultcloud** [berops/claudie#815]
### Motivation

Using external services will make Claudie migrations much easier. Also if users decide to use external service to store sensitive content, they can do that.

### Description

Claudie supports storing Claudie output in external services, by defining option to use external services with correct access keys and or connections strings.

### Exit criteria

- [ ] s3
- [ ] dynamodb
- [ ] mongodb

**Comment by Danielss89** [comment]
I can see this be valuable, as a user might want to move Claudie to a cluster managed by Claudie.
So user sets up a throw-away cluster, installs Claudie, sets up new cluster with Claudie, moves Claudie to new cluster, removes throw-away cluster.
