### ISSUE TITLE
Feature: trigger claudie testing environment via slack

### ISSUE THREAD

**Issue by katapultcloud** [berops/claudie#849]
### Motivation

In order to reduce users provisioning time we can offer a service where a potential user is invited into a slack channel, where they call a bot to provision a simple claudie cluster with node pools located at all cloud providers, at our expense. Kubeconfig will be returned to the user into slack so they can play around in the cluster. After x time we can nuke the cluster. We'll have complete control over the manifest too so we'll know exactly how much it costs per demo.

### Exit criteria

- [ ] cluster is able to be provisioned via slack

**Comment by bernardhalas** [comment]
We don't see much of value in doing this right now. It's not clear which workload could people try to deploy to get something meaningful out of this. And then there were also the security concerns.
