### ISSUE TITLE
Fix the README.md youtube video thumbnail

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#866]
```
$ curl https://markdown-videos.deta.dev/youtube/q4xdAiHYxZQ
Service No Longer Available
```

**Comment by akj2018** [comment]
Hi, I have already fixed this issue. Please assign it to me.

**Comment by MarioUhrik** [comment]
Hi @akj2018 , I had a look at your fix, it looks good. Thanks a lot!

https://github.com/berops/claudie/commit/dbde73b426c00aa86d91c364375cdec94dc4be3d
https://github.com/berops/claudie/blob/dbde73b426c00aa86d91c364375cdec94dc4be3d/README.md

Can you please open a PR for this?

**Comment by akj2018** [comment]
Done!
