### ISSUE TITLE
Chore: Troubleshooting guide

### ISSUE THREAD

**Issue by katapultcloud** [berops/claudie#877]
### Description

Create a troubleshooting guide as a part of ultra detailed docs for claudie.

The link will be active with a new release of Claudie https://docs.claudie.io/latest/troubleshooting.

Related to https://github.com/berops/claudie/issues/835

### Exit criteria

- [ ] Troubleshooting guide exists.

**Comment by katapultcloud** [comment]
- mention MTU problem
- mention blocked IP problem

**Comment by MiroslavRepka** [comment]
- mention start-up issues (terraform not ready due to databases not properly initialised)
- mention where to look for error logs (Frontend -> service that failed)
