### ISSUE TITLE
Feature: Create #claudie channel on Kubernetes Slack workspace

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#968]
### Motivation
Create a `# claudie` channel on the Slack workspace. As the Kubernetes workspace community is large, this might be beneficial for the project itself and its adoption.

### Description
Read the [community rules](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md) and create `# claudie` channel on the Kubernetes Slack workspace accordingly.

### Exit criteria

- [x] Claudie channel is created
- [x] Links are updated
- [x] Claudie workspace is deleted

**Comment by JKBGIT1** [comment]
[PR](https://github.com/kubernetes/community/pull/7449) for creating `#claudie` channel is opened. We are in the middle of the process of signing Corporate CLA.

After signing, there is a need to add comment with `/easycla` in PR

**Comment by JKBGIT1** [comment]
Three weeks ago I assigned a guy from k8s community to give a review on the PR. A minute ago I have pinged him in the comment and ask, whether he can give it a review (following [escalations practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed)).

**Comment by JKBGIT1** [comment]
The links were updated in `infra` and `claudie` repository
