### ISSUE TITLE
Bug: release-docs pipeline fails when pushing to master

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#991]
### Current Behaviour
`release-docs` pipeline fails, when there is a new Changelog file on `release`, because it wants to push updated `mkdocs.yml` file to `master` branch and encounter this error.

```
[master f2b698b] add new changelog file to mkdocs.yml
 1 file changed, 1 insertion(+)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Changes must be made through the merge queue Changes must be made through a pull request.        
To https://github.com/berops/claudie
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/berops/claudie'
```

### Expected Behaviour
Updated `mkdocs.yml` file successfully pushed to `master` branch using `release-docs` pipeline.

### Ways to resolve this

- use a [workaround](https://stackoverflow.com/questions/69263843/how-to-push-to-protected-main-branches-in-a-github-action/72515781#72515781) with someone's PAT in `actions/checkout`. However this actor needs to have `pull request bypass` enabled in claudie repo.
- start adding Changelog files references to `mkdocs.yml` manually and remove pushing to `master` from `release-docs` pipeline.

These approaches were also mentioned on Slack and @Despire was fine with the second one.

**Comment by bernardhalas** [comment]
Could we piggyback with the `mkdocs.yml` update on the release PR somehow, e.g. [here](https://github.com/berops/claudie/pull/989)?

FYI @JKBGIT1 @Despire

**Comment by MarioUhrik** [comment]
Sorry, the idea with a label trigger won't work as discussed here https://berops.slack.com/archives/C04JSCX9YCB/p1692094440724039

Perhaps the pipeline, instead of pushing to master, could push a feature branch, open a new PR, and then a human would manually merge it.
