### ISSUE TITLE
Claudie application metrics

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#994]
Feature for Claudie to expose application-level metrics, that can be monitored with, for example, Prometheus. This feature should allow us to have more in-depth visibility of what Claudie is doing. Example metric ideas:
- number of concurrent jobs executed by a service
- number of clusters/inpuitmanifest currently managed
- number of warnings/errors on which base alerts can be created

**Comment by bernardhalas** [comment]
I'll add a bit more context to this task.

The high-level goal is to provide visibility into the internals of Claudie. So if an enterprise customer adopts this solution, they would like to have a confidence that it operates well and once it breaks, they get alerted appropriately. The observability should be work on from these angles, IMHO:
- functional monitoring (metrics on clusters being operated, nodes being operated, the diffs - clusters/nodes added/removed, error rates, infra modification latencies,...); things to give us useful functional insights into what Claudie is doing
- technical monitoring (metrics on API calls, rates, service latencies, transaction error rates); aspects to give us insights into how Claudie is doing technically
- alerting on the key selected metrics from above
- out-of-the-box dashboard on the above

Exit Criteria:
- [ ] metrics for technical monitoring is proposed and implemented
- [ ] functional monitoring proposed and implemented
- [ ] alert rules proposed
- [ ] dashboard created
