### ISSUE TITLE
Publish Hetzner community tutorial on how to make a Claudie K8s cluster

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#995]
https://community.hetzner.com/tutorials

We can contribute via a tutorial on how to use Claudie to create a Kubernetes cluster on Hetzner.
This will help popularize Claudie, and it might be useful to the Hetzner community.

**Comment by bernardhalas** [comment]
Before contributing the tutorial, it would be a good idea to check if the content will be welcome to avoid wasting the effort.

**Comment by cloudziu** [comment]
Repository link: https://github.com/hetzneronline/community-content
Their [guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md#external-references) are mentioning:
> Please do not just write about a product or software itself. Usually, there is already official documentation with that same information. What you can do, however, is write a tutorial to explain how to use a certain product or software in a specific environment.

> Your tutorial should not include links to or content of small external repositories. The reason for this is that we at Hetzner cannot control any changes or deletions made to those small external repositories. As a result, the submitted tutorial might not work anymore.

I think that we are good to go.
